FROM python:3.7

WORKDIR /usr/src/app

COPY input_data.csv .

COPY csvtojson.py .

COPY test_csvtojson.py .

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m unittest test_csvtojson.py


CMD ["python","./csvtojson.py"]